"""TEI header construction and loss-preserving structural finishing."""
from copy import deepcopy
import re
from lxml import etree
from .document import NS, XML_ID, qn


def element(name, text=None, **attributes):
    node = etree.Element(qn('tei', name), **attributes)
    node.text = text
    return node


def append_text(node, value):
    if not value:
        return
    if len(node):
        node[-1].tail = (node[-1].tail or '') + value
    else:
        node.text = (node.text or '') + value


class TEIHeaderBuilder:
    def build(self, metadata, source_name, source_hash, revision):
        header = element('teiHeader')
        file_desc = etree.SubElement(header, qn('tei', 'fileDesc'))
        titles = etree.SubElement(file_desc, qn('tei', 'titleStmt'))
        titles.append(element('title', metadata.title))
        for author in metadata.authors:
            titles.append(element('author', author))
        for translator in metadata.translators:
            credit = etree.SubElement(titles, qn('tei', 'respStmt'))
            credit.append(element('resp', 'Translation'))
            credit.append(element('name', translator, role='translator'))
        for editor in metadata.editors:
            titles.append(element('editor', editor))
        for label in ('DIGITALIZZAZIONE', 'REVISIONE', 'IMPAGINAZIONE', 'PUBBLICAZIONE'):
            if metadata.fields.get(label):
                credit = etree.SubElement(titles, qn('tei', 'respStmt'))
                credit.append(element('resp', label.title()))
                for name in metadata.fields[label].splitlines():
                    credit.append(element('name', name))
        if metadata.edition_date:
            edition_stmt = etree.SubElement(file_desc, qn('tei', 'editionStmt'))
            edition = etree.SubElement(edition_stmt, qn('tei', 'edition'))
            edition.text = 'Source electronic edition: '
            edition.append(element('date', metadata.edition_date))
        publication = etree.SubElement(file_desc, qn('tei', 'publicationStmt'))
        publication.append(element('authority', 'TEI transcription generated by teify'))
        availability = etree.SubElement(publication, qn('tei', 'availability'), status='unknown')
        for statement in metadata.licences:
            licence = element('licence', statement)
            urls = re.findall(r'(?:https?://|www\.)[^\s<>]+', statement)
            if urls:
                url = urls[0].rstrip('.,;)')
                licence.set('target', url if url.startswith('http') else 'https://' + url)
            availability.append(licence)
        if metadata.rights:
            availability.append(element('p', "Source copyright declaration (DIRITTI D'AUTORE): " + metadata.rights))
        if not len(availability):
            availability.append(element('p', 'No explicit licence statement was identified in the source.'))
        if metadata.fields:
            notes = etree.SubElement(file_desc, qn('tei', 'notesStmt'))
            for label, value in metadata.fields.items():
                notes.append(element('note', value, type='source-metadata', n=label))
        source = etree.SubElement(file_desc, qn('tei', 'sourceDesc'))
        if metadata.source:
            source.append(element('bibl', metadata.source))
        record = etree.SubElement(source, qn('tei', 'bibl'))
        record.append(element('title', source_name))
        record.append(element('idno', source_hash, type='SHA256'))
        encoding = etree.SubElement(header, qn('tei', 'encodingDesc'))
        project = etree.SubElement(encoding, qn('tei', 'projectDesc'))
        project.append(element('p', f'Converted with teify and petrul/tei-stylesheets revision {revision}.'))
        editorial = etree.SubElement(encoding, qn('tei', 'editorialDecl'))
        editorial.append(element('p', 'Source text and boilerplate retained. Metadata extracted from labelled fields or explicit overrides. Heading gaps compressed using an ancestor stack. Explicit verse styles encoded as stanzas and lines. Source styles retained as rend and representable formatting as CSS in style. No legal status inferred from source declarations.'))
        if metadata.language:
            profile = etree.SubElement(header, qn('tei', 'profileDesc'))
            usage = etree.SubElement(profile, qn('tei', 'langUsage'))
            usage.append(element('language', metadata.language, ident=metadata.language))
        return header


class VerseNormalizer:
    """Split line breaks even inside inline spans, preserving inline markup."""
    def split(self, node):
        def shell():
            clone = etree.Element(node.tag, attrib=dict(node.attrib))
            clone.attrib.pop(XML_ID, None)
            return clone
        segments = [shell()]
        segments[0].text = node.text
        for child in node:
            if child.tag == qn('tei', 'lb'):
                segments.append(shell())
            elif child.tag == qn('tei', 'note'):
                clone = deepcopy(child)
                clone.tail = None
                segments[-1].append(clone)
            else:
                pieces = self.split(child)
                segments[-1].append(pieces[0])
                for piece in pieces[1:]:
                    segments.append(shell())
                    segments[-1].append(piece)
            append_text(segments[-1], child.tail)
        return segments

    def normalize(self, root):
        count = 0
        for paragraph in root.xpath('//tei:p[@type="verse-stanza"]', namespaces=NS):
            lines = self.split(paragraph)
            stanza = element('lg', type='stanza')
            for key, value in paragraph.attrib.items():
                if key != 'type':
                    stanza.set(key, value)
            for line in lines:
                line.tag = qn('tei', 'l')
                line.attrib.clear()
                stanza.append(line)
            stanza.tail = paragraph.tail
            paragraph.getparent().replace(paragraph, stanza)
            count += 1
        return count


class DramaNormalizer:
    """Group explicitly styled speakers; retain speech and stage formatting."""
    def normalize(self, root):
        for stage in root.xpath('//tei:p[@type="drama-stage"]', namespaces=NS):
            stage.tag = qn('tei', 'stage')
            stage.attrib.pop('type', None)
        parents = {node.getparent() for node in root.xpath('//tei:p[@type="drama-speaker"]', namespaces=NS)}
        for parent in parents:
            speech = None
            for child in list(parent):
                if child.tag == qn('tei', 'p') and child.get('type') == 'drama-speaker':
                    speech = element('sp')
                    parent.insert(parent.index(child), speech)
                    child.tag = qn('tei', 'speaker')
                    child.attrib.pop('type', None)
                    speech.append(child)
                elif child.tag in (qn('tei','head'), qn('tei','div')):
                    speech = None
                elif speech is not None:
                    speech.append(child)
                elif child.tag == qn('tei','p') and 'font-style: italic' in child.get('style',''):
                    child.tag = qn('tei','stage')
        for paragraph in root.xpath('//tei:sp/tei:p', namespaces=NS):
            value = ''.join(paragraph.itertext()).strip()
            italic = paragraph.xpath('.//tei:hi[contains(@style,"font-style: italic")]', namespaces=NS)
            if value.startswith('(') and value.endswith(')') and italic and value.count('(') == 1:
                paragraph.tag = qn('tei','stage')
                continue
            for span in italic:
                previous = span.getprevious()
                before = (previous.tail or '') if previous is not None else (span.getparent().text or '')
                if previous is not None:
                    before = ''.join(previous.itertext()) + before
                following = span.getnext()
                after = span.tail or ''
                if following is not None:
                    after += ''.join(following.itertext())
                if before.rstrip().endswith('(') and after.lstrip().startswith(')'):
                    span.tag = qn('tei','stage')


class TEIFinalizer:
    def finalize(self, tree, metadata, source_name, source_hash, revision):
        root = tree.getroot()
        header = root.find('tei:teiHeader', NS)
        root.replace(header, TEIHeaderBuilder().build(metadata, source_name, source_hash, revision))
        for span in root.xpath('//tei:head/tei:seg[@type="source-heading"]', namespaces=NS):
            head = span.getparent()
            for key, value in span.attrib.items():
                if key != 'type':
                    head.set(key, value)
            head.text = span.text
            for child in list(span):
                head.append(child)
            head.remove(span)
        identifiers = {node.get(XML_ID) for node in root.xpath('//*[@xml:id]')}
        for reference in root.xpath('//tei:ref[starts-with(@target,"#")]', namespaces=NS):
            target = reference.get('target')[1:]
            if target not in identifiers and 'id_' + target in identifiers:
                reference.set('target', '#id_' + target)
        VerseNormalizer().normalize(root)
        DramaNormalizer().normalize(root)
        body = root.find('tei:text/tei:body', NS)
        # Every top-level block belongs to a division, without reordering it.
        group = None
        for child in list(body):
            if child.tag == qn('tei', 'div'):
                group = None
            else:
                if group is None:
                    group = element('div', type='unsectioned')
                    body.insert(body.index(child), group)
                group.append(child)
        if metadata.language:
            root.set('{http://www.w3.org/XML/1998/namespace}lang', metadata.language)
        return tree
